// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 19/03/2026, 2:24:14 am
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/private/tmp/canlah-website/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/private/tmp/canlah-website/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/private/tmp/canlah-website/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/private/tmp/canlah-website/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/private/tmp/canlah-website/app/plugins/**/*.{js,ts,mjs}","/private/tmp/canlah-website/app/composables/**/*.{js,ts,mjs}","/private/tmp/canlah-website/app/utils/**/*.{js,ts,mjs}","/private/tmp/canlah-website/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/private/tmp/canlah-website/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/private/tmp/canlah-website/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;