<script setup lang="ts">
useSeoMeta({
  title: 'Terms of Service — CANLAH AI',
  description: 'Terms and conditions for using CANLAH AI products including CanMarket, CanService, CanSales, and CanCommerce.',
})
</script>

<template>
  <div>
    <SiteHeader />

    <section class="pt-32 pb-20 px-6">
      <div class="max-w-[800px] mx-auto">

        <div class="mb-12">
          <div class="font-mono text-[10px] text-[#00d4ff] tracking-[4px] mb-3">LEGAL</div>
          <h1 class="font-display font-extrabold text-4xl md:text-5xl text-white leading-tight mb-4">Terms of Service</h1>
          <p class="text-[14px] text-[#5a7099]">Last updated: March 20, 2026</p>
        </div>

        <div class="space-y-8">

          <div class="rounded-2xl border border-white/8 bg-white/[0.025] p-6">
            <h2 class="font-display font-bold text-lg text-white mb-3">1. Acceptance of Terms</h2>
            <p class="text-[14px] text-[#7090b8] leading-relaxed">
              By accessing or using any services provided by CANLAH AI Pte. Ltd. ("CANLAH AI", "we", "us"), including the canlah.ai website, CanMarket platform (app.canmarket.ai), and any related products (collectively, the "Services"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree, do not use our Services.
            </p>
          </div>

          <div class="rounded-2xl border border-white/8 bg-white/[0.025] p-6">
            <h2 class="font-display font-bold text-lg text-white mb-3">2. Description of Services</h2>
            <p class="text-[14px] text-[#7090b8] leading-relaxed">
              CANLAH AI provides AI-powered marketing, sales, service, and commerce agents. Our platform includes Style Genome™ brand memory technology, content generation, campaign automation, and multi-channel publishing capabilities. Services are provided on a credit-based or subscription model as described on our pricing page.
            </p>
          </div>

          <div class="rounded-2xl border border-white/8 bg-white/[0.025] p-6">
            <h2 class="font-display font-bold text-lg text-white mb-3">3. Account Registration</h2>
            <div class="space-y-3 text-[14px] text-[#7090b8] leading-relaxed">
              <p>To use certain features, you must create an account. You agree to:</p>
              <ul class="space-y-2">
                <li class="flex items-start gap-2"><span class="text-[#00d4ff] mt-0.5">•</span> Provide accurate and complete registration information</li>
                <li class="flex items-start gap-2"><span class="text-[#00d4ff] mt-0.5">•</span> Maintain the security of your account credentials</li>
                <li class="flex items-start gap-2"><span class="text-[#00d4ff] mt-0.5">•</span> Promptly notify us of any unauthorized access</li>
                <li class="flex items-start gap-2"><span class="text-[#00d4ff] mt-0.5">•</span> Accept responsibility for all activities under your account</li>
              </ul>
            </div>
          </div>

          <div class="rounded-2xl border border-white/8 bg-white/[0.025] p-6">
            <h2 class="font-display font-bold text-lg text-white mb-3">4. Intellectual Property</h2>
            <div class="space-y-3 text-[14px] text-[#7090b8] leading-relaxed">
              <div>
                <h3 class="font-semibold text-[#a0b8d8] mb-1">Your Content</h3>
                <p>You retain all rights to content you upload to our platform, including brand assets, images, and text. By uploading content, you grant us a limited license to process it for the purpose of providing our Services (including Style Genome™ brand memory encoding).</p>
              </div>
              <div>
                <h3 class="font-semibold text-[#a0b8d8] mb-1">Generated Content</h3>
                <p>Content generated by our AI agents using your brand profile belongs to you. You may use generated content for any lawful commercial purpose.</p>
              </div>
              <div>
                <h3 class="font-semibold text-[#a0b8d8] mb-1">Our Platform</h3>
                <p>The CANLAH AI platform, Style Genome™ technology, and all related intellectual property remain the exclusive property of CANLAH AI Pte. Ltd.</p>
              </div>
            </div>
          </div>

          <div class="rounded-2xl border border-white/8 bg-white/[0.025] p-6">
            <h2 class="font-display font-bold text-lg text-white mb-3">5. Payment & Credits</h2>
            <ul class="space-y-2 text-[14px] text-[#7090b8]">
              <li class="flex items-start gap-2"><span class="text-[#00d4ff] mt-0.5">•</span> Free tier: 50 AI generations per month, no credit card required</li>
              <li class="flex items-start gap-2"><span class="text-[#00d4ff] mt-0.5">•</span> Growth tier: credit-based, pay-as-you-go pricing</li>
              <li class="flex items-start gap-2"><span class="text-[#00d4ff] mt-0.5">•</span> Enterprise tier: custom pricing with dedicated SLA</li>
              <li class="flex items-start gap-2"><span class="text-[#00d4ff] mt-0.5">•</span> Credits are non-refundable once purchased, unless required by law</li>
              <li class="flex items-start gap-2"><span class="text-[#00d4ff] mt-0.5">•</span> We reserve the right to modify pricing with 30 days' notice</li>
            </ul>
          </div>

          <div class="rounded-2xl border border-white/8 bg-white/[0.025] p-6">
            <h2 class="font-display font-bold text-lg text-white mb-3">6. Acceptable Use</h2>
            <p class="text-[14px] text-[#7090b8] leading-relaxed mb-3">You agree not to use our Services to:</p>
            <ul class="space-y-2 text-[14px] text-[#7090b8]">
              <li class="flex items-start gap-2"><span class="text-red-400 mt-0.5">✕</span> Generate illegal, harmful, or misleading content</li>
              <li class="flex items-start gap-2"><span class="text-red-400 mt-0.5">✕</span> Infringe on third-party intellectual property rights</li>
              <li class="flex items-start gap-2"><span class="text-red-400 mt-0.5">✕</span> Attempt to reverse-engineer our AI models or technology</li>
              <li class="flex items-start gap-2"><span class="text-red-400 mt-0.5">✕</span> Circumvent usage limits or security measures</li>
              <li class="flex items-start gap-2"><span class="text-red-400 mt-0.5">✕</span> Resell access to the platform without authorization</li>
            </ul>
          </div>

          <div class="rounded-2xl border border-white/8 bg-white/[0.025] p-6">
            <h2 class="font-display font-bold text-lg text-white mb-3">7. Service Availability</h2>
            <p class="text-[14px] text-[#7090b8] leading-relaxed">
              We strive for high availability but do not guarantee uninterrupted service. We may temporarily suspend access for maintenance, updates, or security reasons. Enterprise customers with SLAs will be governed by their specific agreement terms.
            </p>
          </div>

          <div class="rounded-2xl border border-white/8 bg-white/[0.025] p-6">
            <h2 class="font-display font-bold text-lg text-white mb-3">8. Limitation of Liability</h2>
            <p class="text-[14px] text-[#7090b8] leading-relaxed">
              To the maximum extent permitted by law, CANLAH AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or business opportunities, arising from your use of our Services. Our total liability shall not exceed the amount you paid us in the twelve months preceding the claim.
            </p>
          </div>

          <div class="rounded-2xl border border-white/8 bg-white/[0.025] p-6">
            <h2 class="font-display font-bold text-lg text-white mb-3">9. Termination</h2>
            <p class="text-[14px] text-[#7090b8] leading-relaxed">
              Either party may terminate the agreement at any time. Upon termination, your right to use the Services ceases immediately. We will retain your data for 30 days to allow export, after which it will be permanently deleted. You may request immediate deletion by contacting us.
            </p>
          </div>

          <div class="rounded-2xl border border-white/8 bg-white/[0.025] p-6">
            <h2 class="font-display font-bold text-lg text-white mb-3">10. Governing Law</h2>
            <p class="text-[14px] text-[#7090b8] leading-relaxed">
              These Terms shall be governed by and construed in accordance with the laws of Singapore. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the courts of Singapore.
            </p>
          </div>

          <div class="rounded-2xl border border-white/8 bg-white/[0.025] p-6">
            <h2 class="font-display font-bold text-lg text-white mb-3">11. Changes to Terms</h2>
            <p class="text-[14px] text-[#7090b8] leading-relaxed">
              We may update these Terms from time to time. We will notify registered users of material changes via email at least 30 days before they take effect. Continued use of our Services after changes become effective constitutes acceptance of the updated Terms.
            </p>
          </div>

          <div class="rounded-2xl border border-white/8 bg-white/[0.025] p-6">
            <h2 class="font-display font-bold text-lg text-white mb-3">12. Contact</h2>
            <p class="text-[14px] text-[#7090b8] leading-relaxed">
              For questions about these Terms, contact us at
              <a href="mailto:hello@canlah.ai" class="text-[#00d4ff] hover:underline">hello@canlah.ai</a>.
            </p>
          </div>

        </div>

        <div class="mt-12 text-center">
          <NuxtLink to="/" class="text-[13px] text-[#5a7099] hover:text-[#00d4ff] transition-colors">← Back to homepage</NuxtLink>
        </div>

      </div>
    </section>

    <SiteFooter />
  </div>
</template>
