<template>
  <div class="space-y-8">

    <!-- Intro -->
    <p class="text-[15px] text-[#8aa0c4] leading-[1.8]">
      The AI content race has a speed problem — but not the one you think. Every platform is competing on tokens per second, latency, and throughput. But the brands actually winning with AI aren't the ones generating fastest. They're the ones generating <em class="text-white font-medium">smartest</em> — with memory.
    </p>

    <!-- Pull quote -->
    <div class="border-l-2 border-[#00d4ff] pl-6 py-2">
      <p class="text-[17px] text-white font-display italic leading-relaxed">
        "Speed without memory is just noise at scale."
      </p>
    </div>

    <p class="text-[15px] text-[#8aa0c4] leading-[1.8]">
      Consider this: a marketing team at a global F&B brand was producing 200+ pieces of content per month using three different AI tools. Fast? Absolutely. On-brand? Not even close. Their social feeds looked like they were run by five different companies. The fonts were wrong, the tone shifted between posts, and the visual language was inconsistent enough that their own employees couldn't recognize the brand on Instagram.
    </p>

    <!-- Section -->
    <h2 class="font-display font-bold text-[22px] text-white mt-12 mb-4">The Speed Trap</h2>

    <p class="text-[15px] text-[#8aa0c4] leading-[1.8]">
      Generic AI tools like ChatGPT and Jasper optimize for one thing: getting you an output as quickly as possible. They have no concept of <em class="text-white">your</em> brand. Every prompt starts from zero. Every generation is a coin flip between "close enough" and "completely off."
    </p>

    <p class="text-[15px] text-[#8aa0c4] leading-[1.8]">
      This creates what we call the <strong class="text-white">speed trap</strong>: the faster you generate, the faster you dilute. Each piece of off-brand content doesn't just fail on its own — it actively erodes the brand equity you spent years building. And the worst part? You often don't notice until the damage compounds.
    </p>

    <p class="text-[15px] text-[#8aa0c4] leading-[1.8]">
      A 2025 study by Bain & Company found that brands using AI without brand guardrails saw a measurable decline in brand recall within 6 months. The content was plentiful, but forgettable. Volume without identity is just white noise.
    </p>

    <!-- Section -->
    <h2 class="font-display font-bold text-[22px] text-white mt-12 mb-4">What Brand Memory Actually Means</h2>

    <p class="text-[15px] text-[#8aa0c4] leading-[1.8]">
      Brand memory is the ability for an AI system to <em class="text-white">persistently understand</em> your brand's visual language, tone, style preferences, and creative boundaries — and enforce them automatically on every output.
    </p>

    <p class="text-[15px] text-[#8aa0c4] leading-[1.8]">
      At CANLAH AI, we built this capability into our core technology: <strong class="text-white">Style Genome™</strong>. When you onboard, we encode your brand into a 768-dimensional memory vector — a mathematical representation of everything that makes your brand <em class="text-white">yours</em>. Color palette preferences, typography choices, image composition patterns, tonal consistency, layout tendencies, and hundreds of other signals.
    </p>

    <p class="text-[15px] text-[#8aa0c4] leading-[1.8]">
      Every piece of content generated by CanMarket is checked against this vector. If it doesn't match your brand DNA, it gets caught and corrected before it reaches you. This isn't a style guide PDF that developers ignore — it's an active, mathematical constraint that shapes every pixel and every word.
    </p>

    <!-- Section -->
    <h2 class="font-display font-bold text-[22px] text-white mt-12 mb-4">Memory vs. Speed: The Numbers</h2>

    <p class="text-[15px] text-[#8aa0c4] leading-[1.8]">
      Let's compare two approaches across a typical quarter:
    </p>

    <!-- Comparison mini-table -->
    <div class="rounded-xl border border-white/10 bg-white/[0.02] overflow-hidden">
      <div class="grid grid-cols-3 text-[12px] font-mono">
        <div class="p-3 border-b border-r border-white/8 text-[#4a6a90]">Metric</div>
        <div class="p-3 border-b border-r border-white/8 text-[#4a6a90] text-center">Generic AI</div>
        <div class="p-3 border-b border-white/8 text-[#00d4ff] text-center">With Brand Memory</div>

        <div class="p-3 border-b border-r border-white/8 text-[#7090b8]">Content produced</div>
        <div class="p-3 border-b border-r border-white/8 text-[#7090b8] text-center">600 pieces</div>
        <div class="p-3 border-b border-white/8 text-white text-center">450 pieces</div>

        <div class="p-3 border-b border-r border-white/8 text-[#7090b8]">On-brand rate</div>
        <div class="p-3 border-b border-r border-white/8 text-[#7090b8] text-center">~35%</div>
        <div class="p-3 border-b border-white/8 text-[#00e5a0] text-center font-semibold">92%</div>

        <div class="p-3 border-b border-r border-white/8 text-[#7090b8]">Usable without edits</div>
        <div class="p-3 border-b border-r border-white/8 text-[#7090b8] text-center">~15%</div>
        <div class="p-3 border-b border-white/8 text-[#00e5a0] text-center font-semibold">68%</div>

        <div class="p-3 border-r border-white/8 text-[#7090b8]">Team review hours</div>
        <div class="p-3 border-r border-white/8 text-[#7090b8] text-center">120+ hrs</div>
        <div class="p-3 text-[#00e5a0] text-center font-semibold">~30 hrs</div>
      </div>
    </div>

    <p class="text-[15px] text-[#8aa0c4] leading-[1.8]">
      The generic approach produces more content, but most of it requires heavy editing or gets discarded entirely. The brand-memory approach produces fewer pieces but each one is closer to publish-ready. Net effective output? The memory-based system wins by 3x.
    </p>

    <!-- Section -->
    <h2 class="font-display font-bold text-[22px] text-white mt-12 mb-4">The Compounding Effect</h2>

    <p class="text-[15px] text-[#8aa0c4] leading-[1.8]">
      Brand memory doesn't just improve individual outputs — it compounds over time. Every campaign you run through a memory-aware system teaches it more about what works for your brand. The 768 dimensions get sharper. Edge cases get handled. The AI starts making creative decisions that feel genuinely <em class="text-white">yours</em>, not just "close enough."
    </p>

    <p class="text-[15px] text-[#8aa0c4] leading-[1.8]">
      This is the fundamental difference between a tool and a creative partner. ChatGPT is a tool — it does what you tell it, with no memory of yesterday. A brand-memory AI is a creative partner that gets better at being <em class="text-white">your</em> brand every single day.
    </p>

    <!-- Section -->
    <h2 class="font-display font-bold text-[22px] text-white mt-12 mb-4">What This Means for Your Team</h2>

    <p class="text-[15px] text-[#8aa0c4] leading-[1.8]">
      If your marketing team is currently using generic AI tools, you're likely experiencing one or more of these symptoms: inconsistent visual output, growing review bottlenecks, creative fatigue from fixing AI mistakes, and a nagging sense that your brand is slowly losing its edge.
    </p>

    <p class="text-[15px] text-[#8aa0c4] leading-[1.8]">
      The fix isn't to stop using AI — it's to use AI that remembers who you are.
    </p>

    <!-- Key Takeaways Box -->
    <div class="rounded-2xl border border-[#00d4ff]/20 bg-[#00d4ff]/[0.04] p-6 mt-12">
      <h3 class="font-display font-bold text-[15px] text-[#00d4ff] mb-4 flex items-center gap-2">
        <span>💡</span> Key Takeaways
      </h3>
      <ul class="space-y-2.5 text-[14px] text-[#8aa0c4]">
        <li class="flex items-start gap-2.5"><span class="text-[#00d4ff] mt-0.5 flex-shrink-0">→</span> Speed without brand memory leads to content dilution — volume ≠ value</li>
        <li class="flex items-start gap-2.5"><span class="text-[#00d4ff] mt-0.5 flex-shrink-0">→</span> Style Genome™ encodes brand identity into a 768-dimensional vector that constrains every output</li>
        <li class="flex items-start gap-2.5"><span class="text-[#00d4ff] mt-0.5 flex-shrink-0">→</span> Brand-memory AI produces 3x more usable content than generic tools despite lower raw volume</li>
        <li class="flex items-start gap-2.5"><span class="text-[#00d4ff] mt-0.5 flex-shrink-0">→</span> Memory compounds — the system gets better at being your brand over time</li>
        <li class="flex items-start gap-2.5"><span class="text-[#00d4ff] mt-0.5 flex-shrink-0">→</span> The future isn't faster AI — it's smarter AI that knows who you are</li>
      </ul>
    </div>

    <!-- CTA -->
    <div class="text-center pt-8">
      <p class="text-[14px] text-[#5a7099] mb-4">Ready to give your brand a memory?</p>
      <a href="https://app.canmarket.ai" target="_blank"
        class="inline-flex items-center gap-2 px-7 py-3 rounded-full font-semibold text-sm bg-gradient-to-r from-[#0d47e0] to-[#00d4ff] text-white hover:shadow-[0_0_30px_rgba(0,212,255,0.4)] transition-all hover:scale-[1.03]">
        Try CanMarket Free <span>→</span>
      </a>
    </div>

  </div>
</template>
